[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"

[rpc_endpoints]
arc_testnet = "${ARC_TESTNET_RPC_URL}"
local = "http://127.0.0.1:8545"
og_testnet = "https://evmrpc-testnet.0g.ai"

[etherscan]
og_testnet = { key = "${ETHERSCAN_API_KEY}", chain = 16602, url = "https://chainscan-galileo.0g.ai/open/api" }
